"""first commit

Revision ID: 2d4d3f6bda84
Revises: 
Create Date: 2023-06-25 01:35:52.459003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4d3f6bda84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
