"""add inital field order

Revision ID: 3232ad9036c9
Revises: 7132840f877c
Create Date: 2023-06-30 14:19:05.690449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3232ad9036c9'
down_revision = '7132840f877c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
