"""Initial

Revision ID: 427a05c2a3c6
Revises: 
Create Date: 2023-06-25 19:46:14.345066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '427a05c2a3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.create_unique_constraint(None, 'cart', ['user_id'])
    op.drop_constraint('cart_product_cart_id_fkey', 'cart_product', type_='foreignkey')
    op.create_foreign_key(None, 'cart_product', 'cart', ['cart_id'], ['cart_id'])
    op.drop_constraint('product_description_key', 'product', type_='unique')
    op.drop_constraint('product_image_key', 'product', type_='unique')
    op.drop_constraint('product_order_status_key', 'product', type_='unique')
    op.drop_constraint('product_price_key', 'product', type_='unique')
    op.alter_column('role', 'id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('user_cart_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'cart_id')
    op.drop_constraint('user_role_users_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_users_id_fkey', 'user_role', 'users', ['users_id'], ['id'])
    op.add_column('user', sa.Column('cart_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_cart_id_fkey', 'user', 'cart', ['cart_id'], ['cart_id'])
    op.alter_column('role', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('product_price_key', 'product', ['price'])
    op.create_unique_constraint('product_order_status_key', 'product', ['order_status'])
    op.create_unique_constraint('product_image_key', 'product', ['image'])
    op.create_unique_constraint('product_description_key', 'product', ['description'])
    op.drop_constraint(None, 'cart_product', type_='foreignkey')
    op.create_foreign_key('cart_product_cart_id_fkey', 'cart_product', 'order', ['cart_id'], ['order_id'])
    op.drop_constraint(None, 'cart', type_='unique')
    op.create_table('users',
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='users_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###
