"""add inital field cart

Revision ID: 67b9aaf80018
Revises: af20f2c7bec9
Create Date: 2023-06-30 13:50:04.250648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b9aaf80018'
down_revision = 'af20f2c7bec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
