"""add inital field cart

Revision ID: 7132840f877c
Revises: 67b9aaf80018
Create Date: 2023-06-30 13:52:11.946782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7132840f877c'
down_revision = '67b9aaf80018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
