"""add inital field

Revision ID: af20f2c7bec9
Revises: dde987c3b3f7
Create Date: 2023-06-30 13:44:24.097663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af20f2c7bec9'
down_revision = 'dde987c3b3f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
