"""add inital table

Revision ID: dde987c3b3f7
Revises: ae6b6b65ddd6
Create Date: 2023-06-30 13:27:27.219673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde987c3b3f7'
down_revision = 'ae6b6b65ddd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_product_check', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_product_check', 'quantity')
    # ### end Alembic commands ###
